poses:
  grip: [-0.01677261411166551, -0.020751964806212577, -0.8435874406589392, -0.045926770046776255, -0.6519463250437423, -0.02445103901637724]
  high1: [-0.015428710587629874, -0.005602506898901798, 0.07335618846132168, 0.0016266343776782932, -1.5968784903812976, -0.016781135076949116]
  high2: [1.592560582567266, 0.030054569719342356, -0.029426251188624398, -0.0075772503496351895, -1.5800047017145555, -0.01831511586483492]
  low1:  [1.4017786420317657, -0.23052308760341106, -0.6880786043062445, -0.05513065477409018, -0.667286132922599, -0.03979084689523393]
