poses:
  grip: [0.014084807063594239, -0.10019935235699445, -0.7348185216746527, -0.00245106016859847, -0.7854026535897933, -0.05819861634986134]
  place: [1.3434846450151552, 0.14025465869026432, -0.9643467716044269, 0.17956840577241273, -0.15340256898090932, -0.016781135076949116]

